### ISSUE TITLE
Arch Linux - Didn't find the color scheme

### ISSUE THREAD

**Issue by DenysMb** [tantalising/plasma-accent-color-changer#3]
When using the AppImage or converting the deb to Arch Linux package, when we tries to change the color, we get this error:
```
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Error! Didn't find the color scheme!
#0      getCurrentlySetThemePath (package:kolorify/color_scheme_read_and_write_utils.dart:46)
<asynchronous suspension>
#1      generateColorScheme (package:kolorify/color_scheme_change_utils.dart:12)
<asynchronous suspension>
#2      applyColorScheme (package:kolorify/general_utils.dart:119)
<asynchronous suspension>
#3      ColorCard.handleTap (package:kolorify/color_grid_ui.dart:89)
<asynchronous suspension>
```

**Comment by tantalising** [comment]
Probably this has been already fixed. I will make a new release within tomorrow and then if the issue still persists then I will look for the problem.

**Comment by tantalising** [comment]
Check out the new release and if the issue is still there then open it again.
